# Generated by Django 6.0.4 on 2026-04-24 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidatos', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_postulacion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('V', 'Vista'), ('PRE', 'Preseleccionado'), ('N', 'No preseleccionado'), ('E', 'En_proceso'), ('F', 'Finalista'), ('D', 'Descartado')], default='P', max_length=3)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candidatos.candidato')),
            ],
            options={
                'db_table': 'postulaciones',
            },
        ),
        migrations.CreateModel(
            name='PostulacionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('llave', models.CharField(max_length=255, unique=True)),
                ('postulacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vacantes.postulacion')),
            ],
            options={
                'db_table': 'postulaciones_token',
            },
        ),
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('anio_experiencia', models.IntegerField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('nivel_educativo', models.CharField(choices=[('S', 'Sin nivel educativo'), ('P', 'Primaria'), ('B', 'Bachillerato'), ('TE', 'Tecnico'), ('TO', 'Tecnologo'), ('PR', 'Profesional'), ('M', 'Maestria')], default='S', max_length=2)),
                ('tipo_contrato', models.CharField(choices=[('P', 'Prestacion de servicios'), ('O', 'Obra o labor'), ('D', 'Definido'), ('I', 'Indefinido')], default='P', max_length=1)),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
                ('descripcion_cargo', models.TextField()),
                ('compania', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.compania')),
            ],
            options={
                'db_table': 'vacantes',
            },
        ),
        migrations.AddField(
            model_name='postulacion',
            name='vacante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vacantes.vacante'),
        ),
    ]
