# Generated by Django 6.0.4 on 2026-05-10 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VVacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compania_id', models.IntegerField()),
                ('compania_descripcion', models.CharField(max_length=255)),
                ('id_interno', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('unidad_id', models.IntegerField()),
                ('unidad_descripcion', models.CharField(max_length=255)),
                ('unidad_especialidad', models.CharField(max_length=150, null=True)),
                ('anio_experiencia', models.IntegerField(null=True)),
                ('salario_minimo', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('salario_maximo', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('estado_id', models.IntegerField()),
                ('estado_descripcion', models.CharField(max_length=100)),
                ('tipo_contrato_id', models.IntegerField()),
                ('tipo_contrato_descripcion', models.CharField(max_length=100)),
                ('ind_activa', models.BooleanField()),
                ('ind_publicada', models.BooleanField()),
                ('fecha_publicacion', models.DateTimeField(null=True)),
                ('fecha_creacion', models.DateTimeField()),
                ('usuario_creacion', models.IntegerField()),
                ('fecha_modificacion', models.DateTimeField(null=True)),
                ('usuario_modificacion', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'v_vacante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoVacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'estado_vacante',
            },
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_contrato',
            },
        ),
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_interno', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('anio_experiencia', models.IntegerField(blank=True, null=True)),
                ('salario_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('salario_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('ind_activa', models.BooleanField(default=True)),
                ('ind_publicada', models.BooleanField(default=False)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('compania', models.ForeignKey(db_column='compania', on_delete=django.db.models.deletion.CASCADE, related_name='vacantes', to='empresa.compania')),
                ('estado', models.ForeignKey(db_column='estado', on_delete=django.db.models.deletion.PROTECT, related_name='vacantes', to='vacantes.estadovacante')),
                ('tipo_contrato', models.ForeignKey(db_column='tipo_contrato', on_delete=django.db.models.deletion.PROTECT, related_name='vacantes', to='vacantes.tipocontrato')),
                ('unidad', models.ForeignKey(db_column='unidad', on_delete=django.db.models.deletion.PROTECT, related_name='vacantes', to='empresa.unidadorg')),
            ],
            options={
                'db_table': 'vacante',
                'unique_together': {('compania', 'id_interno')},
            },
        ),
    ]
