# Generated by Django 6.0.4 on 2026-04-22 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=180)),
                ('NIT', models.CharField(max_length=20, unique=True)),
                ('telefono_corporativo', models.CharField(max_length=15)),
                ('email_corporativo', models.EmailField(max_length=180, unique=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'companies',
            },
        ),
    ]
