# Generated by Django 6.0.4 on 2026-05-09 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        ('vacantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPostulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'estado_postulacion',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_documento',
            },
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_interno', models.IntegerField(help_text='Identificador secuencial dentro de la compañía')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('compania', models.ForeignKey(db_column='compania', on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='empresa.compania')),
            ],
            options={
                'db_table': 'candidato',
            },
        ),
        migrations.CreateModel(
            name='AnexoCandidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_interno', models.IntegerField(help_text='Identificador secuencial del anexo dentro del candidato')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('tipo_archivo', models.CharField(max_length=10)),
                ('tamanio_bytes', models.BigIntegerField(blank=True, null=True)),
                ('ruta_almacenamiento', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('compania', models.ForeignKey(db_column='compania', on_delete=django.db.models.deletion.CASCADE, related_name='anexos_candidato', to='empresa.compania')),
                ('candidato', models.ForeignKey(db_column='candidato', on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='candidatos.candidato')),
            ],
            options={
                'db_table': 'anexo_candidato',
            },
        ),
        migrations.CreateModel(
            name='DatosCandidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(blank=True, max_length=30, null=True)),
                ('primer_nombre', models.CharField(max_length=80)),
                ('segundo_nombre', models.CharField(blank=True, max_length=80, null=True)),
                ('primer_apellido', models.CharField(max_length=80)),
                ('segundo_apellido', models.CharField(blank=True, max_length=80, null=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('candidato', models.OneToOneField(db_column='candidato', on_delete=django.db.models.deletion.CASCADE, related_name='datos', to='candidatos.candidato')),
                ('compania', models.ForeignKey(db_column='compania', on_delete=django.db.models.deletion.CASCADE, related_name='datos_candidatos', to='empresa.compania')),
            ],
            options={
                'db_table': 'datos_candidato',
            },
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_interno', models.IntegerField(help_text='Identificador secuencial dentro de la compañía')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_postulacion', models.DateTimeField()),
                ('usuario_postulacion', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('candidato', models.ForeignKey(db_column='candidato', on_delete=django.db.models.deletion.PROTECT, related_name='postulaciones', to='candidatos.candidato')),
                ('compania', models.ForeignKey(db_column='compania', on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='empresa.compania')),
                ('estado', models.ForeignKey(db_column='estado', on_delete=django.db.models.deletion.PROTECT, related_name='postulaciones', to='candidatos.estadopostulacion')),
                ('vacante', models.ForeignKey(db_column='vacante', on_delete=django.db.models.deletion.PROTECT, related_name='postulaciones', to='vacantes.vacante')),
            ],
            options={
                'db_table': 'postulacion',
            },
        ),
        migrations.CreateModel(
            name='PostulacionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('llave', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('compania', models.ForeignKey(db_column='compania', on_delete=django.db.models.deletion.CASCADE, related_name='postulacion_tokens', to='empresa.compania')),
            ],
            options={
                'db_table': 'postulacion_token',
            },
        ),
    ]
