# Generated by Django 6.0.4 on 2026-04-24 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'candidatos',
            },
        ),
        migrations.CreateModel(
            name='InformacionEducativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion_educativa', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=80)),
                ('descripcion_educativa', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('nivel_educativo', models.CharField(choices=[('S', 'Sin nivel educativo'), ('P', 'Primaria'), ('B', 'Bachillerato'), ('TE', 'Tecnico'), ('TO', 'Tecnologo'), ('PR', 'Profesional'), ('M', 'Maestria')], default='S', max_length=2)),
                ('estado', models.CharField(choices=[('CR', 'En curso'), ('CN', 'Concluido'), ('I', 'Interrumpido')], default='CR', max_length=2)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candidatos.candidato')),
            ],
            options={
                'db_table': 'informaciones_educativas',
            },
        ),
        migrations.CreateModel(
            name='InformacionLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumen_profesional', models.TextField(blank=True, null=True)),
                ('candidato', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='candidatos.candidato')),
            ],
            options={
                'db_table': 'informaciones_laborales',
            },
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('descripcion_experiencia', models.TextField(blank=True, null=True)),
                ('cargo', models.CharField(max_length=80)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('informacion_laboral', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candidatos.informacionlaboral')),
            ],
            options={
                'db_table': 'experiencias',
            },
        ),
        migrations.CreateModel(
            name='InformacionPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('candidato', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='candidatos.candidato')),
            ],
            options={
                'db_table': 'informaciones_personales',
            },
        ),
    ]
