# Generated by Django 6.0.4 on 2026-05-09 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidatos', '0001_initial'),
        ('evaluacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulaciontoken',
            name='evaluacion',
            field=models.ForeignKey(blank=True, db_column='evaluacion', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tokens', to='evaluacion.evaluacion'),
        ),
        migrations.AddField(
            model_name='postulaciontoken',
            name='postulacion',
            field=models.ForeignKey(db_column='postulacion', on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='candidatos.postulacion'),
        ),
        migrations.AddField(
            model_name='datoscandidato',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, db_column='tipo_documento', null=True, on_delete=django.db.models.deletion.PROTECT, to='candidatos.tipodocumento'),
        ),
        migrations.AlterUniqueTogether(
            name='candidato',
            unique_together={('compania', 'id_interno')},
        ),
        migrations.AlterUniqueTogether(
            name='anexocandidato',
            unique_together={('compania', 'candidato', 'id_interno')},
        ),
        migrations.AlterUniqueTogether(
            name='postulacion',
            unique_together={('compania', 'id_interno')},
        ),
        migrations.AlterUniqueTogether(
            name='postulaciontoken',
            unique_together={('compania', 'postulacion')},
        ),
    ]
