# Generated by Django 6.0.4 on 2026-04-22 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=80)),
                ('descripcion_rol', models.CharField(max_length=180)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vista', models.CharField(max_length=80)),
                ('descripcion_modulo', models.CharField(max_length=180)),
                ('roles', models.ManyToManyField(db_table='rol_modulo', related_name='modulos', to='usuarios.rol')),
            ],
            options={
                'db_table': 'modulos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_query_name='rol', to='usuarios.rol')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
