# Generated by Django 6.0.4 on 2026-05-09 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidatos', '0001_initial'),
        ('empresa', '0001_initial'),
        ('vacantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('criterio_a', models.FloatField(default=1.0)),
                ('criterio_b', models.FloatField(default=0.0)),
                ('criterio_c', models.FloatField(default=0.0)),
                ('ind_activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'pregunta',
            },
        ),
        migrations.CreateModel(
            name='EstadoIntento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'estado_intento',
            },
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('dificultad', models.FloatField(default=0.0)),
                ('discriminacion', models.FloatField(default=1.0)),
                ('adivinabilidad', models.FloatField(default=0.0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'habilidad',
            },
        ),
        migrations.CreateModel(
            name='ControlUso',
            fields=[
                ('pregunta', models.OneToOneField(db_column='pregunta', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='control_uso', serialize=False, to='evaluacion.pregunta')),
                ('tiempo_uso', models.IntegerField(default=0)),
                ('fecha_ultimo_uso', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'control_uso',
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_interno', models.IntegerField(help_text='Identificador secuencial dentro de la compañía')),
                ('descripcion', models.CharField(max_length=255)),
                ('ind_activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('compania', models.ForeignKey(db_column='compania', on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='empresa.compania')),
            ],
            options={
                'db_table': 'evaluacion',
                'unique_together': {('compania', 'id_interno')},
            },
        ),
        migrations.AddField(
            model_name='pregunta',
            name='habilidad',
            field=models.ForeignKey(db_column='habilidad', on_delete=django.db.models.deletion.PROTECT, related_name='preguntas', to='evaluacion.habilidad'),
        ),
        migrations.CreateModel(
            name='Intento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_interno', models.IntegerField(help_text='Identificador secuencial dentro de la compañía')),
                ('habilidad_estim', models.FloatField(blank=True, null=True)),
                ('error_estandar', models.FloatField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('candidato', models.ForeignKey(db_column='candidato', on_delete=django.db.models.deletion.PROTECT, related_name='intentos', to='candidatos.candidato')),
                ('compania', models.ForeignKey(db_column='compania', on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='empresa.compania')),
                ('estado', models.ForeignKey(db_column='estado', on_delete=django.db.models.deletion.PROTECT, related_name='intentos', to='evaluacion.estadointento')),
                ('evaluacion', models.ForeignKey(db_column='evaluacion', on_delete=django.db.models.deletion.PROTECT, related_name='intentos', to='evaluacion.evaluacion')),
                ('postulacion', models.ForeignKey(db_column='postulacion', on_delete=django.db.models.deletion.PROTECT, related_name='intentos', to='candidatos.postulacion')),
            ],
            options={
                'db_table': 'intento',
                'unique_together': {('compania', 'id_interno')},
            },
        ),
        migrations.CreateModel(
            name='HistorialHabilidadEstim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad_estim', models.FloatField()),
                ('error_estandar', models.FloatField()),
                ('paso', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('compania', models.ForeignKey(db_column='compania', on_delete=django.db.models.deletion.CASCADE, related_name='historiales_habilidad', to='empresa.compania')),
                ('intento', models.ForeignKey(db_column='intento', on_delete=django.db.models.deletion.CASCADE, related_name='historial_habilidad', to='evaluacion.intento')),
            ],
            options={
                'db_table': 'historial_habilidad_estim',
                'ordering': ['intento', 'paso'],
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('ind_correcta', models.BooleanField(default=False)),
                ('peso', models.FloatField(default=0.0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('pregunta', models.ForeignKey(db_column='pregunta', on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='evaluacion.pregunta')),
            ],
            options={
                'db_table': 'respuesta',
            },
        ),
        migrations.CreateModel(
            name='EvaluacionVacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('ind_activa', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('compania', models.ForeignKey(db_column='compania', on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion_vacantes', to='empresa.compania')),
                ('evaluacion', models.ForeignKey(db_column='evaluacion', on_delete=django.db.models.deletion.PROTECT, related_name='vacantes_asignadas', to='evaluacion.evaluacion')),
                ('vacante', models.ForeignKey(db_column='vacante', on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_vacante', to='vacantes.vacante')),
            ],
            options={
                'db_table': 'evaluacion_vacante',
                'unique_together': {('compania', 'vacante', 'evaluacion')},
            },
        ),
        migrations.CreateModel(
            name='EvaluacionHabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=0)),
                ('obligatoria', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('compania', models.ForeignKey(db_column='compania', on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion_habilidades', to='empresa.compania')),
                ('evaluacion', models.ForeignKey(db_column='evaluacion', on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to='evaluacion.evaluacion')),
                ('habilidad', models.ForeignKey(db_column='habilidad', on_delete=django.db.models.deletion.PROTECT, related_name='evaluaciones', to='evaluacion.habilidad')),
            ],
            options={
                'db_table': 'evaluacion_habilidad',
                'ordering': ['orden'],
                'unique_together': {('compania', 'evaluacion', 'habilidad')},
            },
        ),
        migrations.CreateModel(
            name='RespuestaCandidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_respuesta', models.IntegerField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('compania', models.ForeignKey(db_column='compania', on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_candidato', to='empresa.compania')),
                ('intento', models.ForeignKey(db_column='intento', on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_candidato', to='evaluacion.intento')),
                ('pregunta', models.ForeignKey(db_column='pregunta', on_delete=django.db.models.deletion.PROTECT, related_name='respuestas_candidato', to='evaluacion.pregunta')),
                ('respuesta', models.ForeignKey(db_column='respuesta', on_delete=django.db.models.deletion.PROTECT, related_name='selecciones_candidato', to='evaluacion.respuesta')),
            ],
            options={
                'db_table': 'respuesta_candidato',
                'unique_together': {('compania', 'intento', 'pregunta')},
            },
        ),
    ]
