# Generated by Django 6.0.4 on 2026-05-28 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VCompania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('nit', models.CharField(max_length=20)),
                ('objeto_social', models.TextField(null=True)),
                ('representante_legal', models.CharField(max_length=150, null=True)),
                ('direccion', models.CharField(max_length=255, null=True)),
                ('telefono', models.CharField(max_length=20, null=True)),
                ('ind_activa', models.BooleanField()),
                ('ind_evaluacion_vacante', models.BooleanField()),
                ('fecha_creacion', models.DateTimeField()),
                ('usuario_creacion', models.IntegerField()),
                ('fecha_modificacion', models.DateTimeField(null=True)),
                ('usuario_modificacion', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'v_compania',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VUnidadOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compania_id', models.IntegerField()),
                ('compania_descripcion', models.CharField(max_length=255)),
                ('compania_nit', models.CharField(max_length=20)),
                ('id_interno', models.IntegerField()),
                ('descripcion', models.CharField(max_length=255)),
                ('especialidad', models.CharField(max_length=150, null=True)),
                ('fecha_creacion', models.DateTimeField()),
                ('usuario_creacion', models.IntegerField()),
                ('fecha_modificacion', models.DateTimeField(null=True)),
                ('usuario_modificacion', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'v_unidad_org',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Compania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('nit', models.CharField(max_length=20, unique=True)),
                ('objeto_social', models.TextField(blank=True, null=True)),
                ('representante_legal', models.CharField(blank=True, max_length=150, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('ind_activa', models.BooleanField(default=True)),
                ('ind_evaluacion_vacante', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'compania',
            },
        ),
        migrations.CreateModel(
            name='CompaniaEliminada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compania_id', models.IntegerField(help_text='ID original de la compañía eliminada')),
                ('descripcion', models.CharField(max_length=255)),
                ('nit', models.CharField(max_length=20)),
                ('objeto_social', models.TextField(blank=True, null=True)),
                ('representante_legal', models.CharField(blank=True, max_length=150, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('ind_activa', models.BooleanField()),
                ('ind_evaluacion_vacante', models.BooleanField()),
                ('fecha_creacion_original', models.DateTimeField()),
                ('usuario_creacion_original', models.IntegerField()),
                ('fecha_eliminacion', models.DateTimeField(help_text='Timestamp exacto de la eliminación')),
                ('usuario_eliminacion', models.IntegerField(help_text='ID del usuario que ejecutó la eliminación')),
                ('total_usuarios_eliminados', models.IntegerField(default=0)),
                ('total_analistas_eliminados', models.IntegerField(default=0)),
                ('total_unidades_eliminadas', models.IntegerField(default=0)),
                ('total_vacantes_eliminadas', models.IntegerField(default=0)),
                ('total_candidatos_eliminados', models.IntegerField(default=0)),
                ('total_postulaciones_eliminadas', models.IntegerField(default=0)),
                ('total_evaluaciones_eliminadas', models.IntegerField(default=0)),
                ('total_habilidades_eliminadas', models.IntegerField(default=0)),
                ('total_preguntas_eliminadas', models.IntegerField(default=0)),
                ('total_intentos_eliminados', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Compañía Eliminada',
                'verbose_name_plural': 'Compañías Eliminadas',
                'db_table': 'compania_eliminada',
                'ordering': ['-fecha_eliminacion'],
            },
        ),
        migrations.CreateModel(
            name='UnidadOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_interno', models.IntegerField()),
                ('descripcion', models.CharField(max_length=255)),
                ('especialidad', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('compania', models.ForeignKey(db_column='compania', on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='empresa.compania')),
            ],
            options={
                'db_table': 'unidad_org',
                'unique_together': {('compania', 'id_interno')},
            },
        ),
    ]
