# Generated by Django 6.0.4 on 2026-05-09 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('nit', models.CharField(max_length=20, unique=True)),
                ('objeto_social', models.TextField(blank=True, null=True)),
                ('representante_legal', models.CharField(blank=True, max_length=150, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('ind_activa', models.BooleanField(default=True)),
                ('ind_evaluacion_vacante', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'compania',
            },
        ),
        migrations.CreateModel(
            name='UnidadOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_interno', models.IntegerField(help_text='Identificador secuencial dentro de la compañía')),
                ('descripcion', models.CharField(max_length=255)),
                ('especialidad', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('compania', models.ForeignKey(db_column='compania', on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='empresa.compania')),
            ],
            options={
                'db_table': 'unidad_org',
                'unique_together': {('compania', 'id_interno')},
            },
        ),
    ]
