# Generated by Django 6.0.4 on 2026-05-09 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('nombre_aplicacion', models.CharField(max_length=150)),
                ('ind_visible', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
                ('icono', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'modulo',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='RolModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rol_modulo',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_interno', models.IntegerField(help_text='Identificador secuencial dentro de la compañía')),
                ('login', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=150)),
                ('ind_super_usuario', models.BooleanField(default=False)),
                ('ind_activo', models.BooleanField(default=True)),
                ('ind_bloqueo', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Analista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_interno', models.IntegerField(help_text='Identificador secuencial dentro de la compañía')),
                ('numero_documento', models.CharField(blank=True, max_length=30, null=True)),
                ('primer_nombre', models.CharField(max_length=80)),
                ('segundo_nombre', models.CharField(blank=True, max_length=80, null=True)),
                ('primer_apellido', models.CharField(max_length=80)),
                ('segundo_apellido', models.CharField(blank=True, max_length=80, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('cargo', models.CharField(blank=True, max_length=120, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.IntegerField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('compania', models.ForeignKey(db_column='compania', on_delete=django.db.models.deletion.CASCADE, related_name='analistas', to='empresa.compania')),
            ],
            options={
                'db_table': 'analista',
            },
        ),
    ]
