# Generated by Django 6.0.4 on 2026-05-10 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acceso', '0001_initial'),
        ('candidatos', '0001_initial'),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analista',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, db_column='tipo_documento', null=True, on_delete=django.db.models.deletion.PROTECT, to='candidatos.tipodocumento'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='modulo_padre',
            field=models.ForeignKey(blank=True, db_column='modulo_padre', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos', to='acceso.modulo'),
        ),
        migrations.AddField(
            model_name='rolmodulo',
            name='modulo',
            field=models.ForeignKey(db_column='modulo', on_delete=django.db.models.deletion.CASCADE, to='acceso.modulo'),
        ),
        migrations.AddField(
            model_name='rolmodulo',
            name='rol',
            field=models.ForeignKey(db_column='rol', on_delete=django.db.models.deletion.CASCADE, to='acceso.rol'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='analista',
            field=models.ForeignKey(blank=True, db_column='analista', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='acceso.analista'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='compania',
            field=models.ForeignKey(db_column='compania', on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='empresa.compania'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(db_column='rol', on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='acceso.rol'),
        ),
        migrations.AlterUniqueTogether(
            name='analista',
            unique_together={('compania', 'id_interno')},
        ),
        migrations.AlterUniqueTogether(
            name='rolmodulo',
            unique_together={('rol', 'modulo')},
        ),
        migrations.AlterUniqueTogether(
            name='usuario',
            unique_together={('compania', 'id_interno')},
        ),
    ]
